### ISSUE TITLE
How to apply the slicing Wasserstein loss on irregular areas?

### ISSUE THREAD

**Issue by sunshineatnoon** [tchambon/A-Sliced-Wasserstein-Loss-for-Neural-Texture-Synthesis#1]
Hi, Thanks for open-sourcing the project! If I understand the algorithm correctly, the current Slicing loss requires equal sized input texture and output image. So how could I apply it to an irregular area like the one shown in Fig.10 in the paper? Also, could you elaborate a little bit more about how to get the tag? Thanks!

**Comment by tchambon** [comment]
Hi. Sorry for the answer delay.
Yes, the loss requires equal sized input and output. But it is easy to generate bigger/smaller output: you only have to tile (or resample) the input to the desired output shape.
As for the binary mask (figure 10), you have to create it (for instance: background part with a tag value of 1000 and your subject with a tag value of 2000 => cluster will automatically be created after sorting, as explained in section 5 "Spatial Constraints Via User-Defined Tags").
